### ISSUE TITLE
테스트케이스와 제한시간

### ISSUE THREAD

**Issue by jeongm-in** [cppWarrior/Algorithm#2]
보통 문제 제한시간을 보면 1초 또는 2초안에 실행이 되어야 합니다. 

이 1초 또는 2초 시간제한은 

전체 테스트케이스를 다 돌렸을 때 누적시간이 제한을 넘지 않아야 하는건가요?

아니면 테스트케이스 중에서 가장 긴 테스트케이스를 돌렸을 때 시간이 제한시간을 넘지 않아야 하는건가요?

**Comment by MoonHyuk** [comment]
https://www.acmicpc.net/blog/view/55

이 글의 **BOJ 작동 원리** 부분을 읽으시면 될거 같아요. 
BOJ나 UVAOJ나 작동 방식은 같을테니..

**Comment by jeongm-in** [comment]
두번째가 맞군요 

> 시간 제한은 각 파일마다 따로따로 적용됩니다. 즉 시간 제한이 1초면 첫 번째 파일에 1초, 두 번째 파일에 1초, ..., 마지막 파일에 1초 이내가 걸려야 합니다. 채점 현황에서 볼 수 있는 "시간"은 가장 오래 걸린 파일에서의 구동 시간을 나타냅니다.

다른 자잘한 팁도 많아서 몇개 더 배웠습니다
