### ISSUE TITLE
for(auto &i : vector) {} 에 대하여

### ISSUE THREAD

**Issue by jeongm-in** [cppWarrior/Algorithm#3]
`for(auto &i : vector) {}` 이 구문을 뭐라고 부르나요? 

이 구문은 iterable을 정방향으로 진행하는데 가끔씩 역순으로 바로 iterate할 수 있었으면 좋겠다는 생각이 드네요. 

지금까지는 iterable을 역순으로 바꾼 다음에 위 구문을 사용해서 풀었는데

혹시 이런 중간과정을 거치지 않고 바로 사용할 수 있는 구문이 있거나 이 구문의 이름을 알려주시면 찾아보겠습니다

**Comment by MoonHyuk** [comment]
range based for라고 부릅니다.
역순으로 순회하고 싶으면 그냥
`for (int i = n - 1; i >= 0; i --) {cout << v[i];}` 을 쓰는게 어떨까요?

**Comment by jeongm-in** [comment]
생각해보니 굳-이 저 구문을 꼭 쓸 필요는 없겠네요
