### ISSUE TITLE
732번 Anagrams by Stack 

### ISSUE THREAD

**Issue by jeongm-in** [cppWarrior/Algorithm#4]
아무리봐도 732번 anagrams by stack이 이해가 안되네요ㅠㅠ stack 은 위에 얹고 위에서 빼는 것 아닌가요? 

요약하면 

소스와 타겟의 top이 
1. 왼쪽인가? 
2. 오른쪽인가?

1. 소스 단어에 i / o 를 해서 타겟을 만드는 것인지

2. i를 하면 소스 단어의 가장 위에 있는 글자를 비어있는 스택에다 푸시하고 o를 하면 소스 단어의 가장 위에 있는 글자를 팝하는지

3. i를 하면 소스 단어의 가장 위에 있는 글자를 팝하고 비어있는 스택에다 푸시하고 o를 하면 소스 단어의 가장 위에 있는 글자를 다른 스택에 푸시하지 않고 팝하는지

예시에 source :  e r i c 에서 i i o i o i o o 를 하면 target : r i c e가 된다는데 어떻게 이게 되는거죠? 

i 를 하고 o를 하면 원래 단어가 남는 것 아닌가요? 

T R O T -> T O R T [ i o i i o o i o ] 같은 경우에는
i from TROT : T
o from TROT = TRO
i i from TRO : T O R
o o from TRO = T
i from T : T O R T
o from T = blank 

T R O T -> T O R T [ i i i i o o o o ]
i i i i from T R O T : T O R T
o o o o from T R O T = blank 
인 것 같은데요.

그런데 다른 예시 입력들은 좀처럼 이해가 안 됩니다.
단어의 탑이 왼쪽이냐 오른쪽이냐, 비어있는 스택에다 소스 단어에 i/o를 해서 타겟을 만드느냐 / 소스에 i/o를 해서 타겟을 만드느냐를 모르겠어서  다 해봤는데 죄다 틀렸습니다. 

제가 이해한 것은
i :  소스의 가장 위에 있는 글자를 비어있는 스택에다가 푸시
o : 소스의 가장 위에 있는 글자를 팝

e r i c (top)
e r i c - > r i c e [ i i o i o i o o ]
i i from e r i c : c i 
o from e r i c = e r i
i from e r i : c i i
o from e r i = e r
i from e r = c i i r e 
o o from e r = blank

(top) e r i c 
e r i c -> r i c e [ i i o i o i o o ]
i i from e r i c : r e
o from e r i c = r i c
i from r i c : r r e
o from r i c = i c
i from i c : i r r e
o o from i c = blank

혹시나 소스 단어에 i, o 를 해서 타겟 단어를 만드는 것인가 싶어서 이렇게도 해보았습니다. 
이 때는 
i :  소스의 가장 위에 있는 글자를 소스의 가장 위에 푸시한다
o : 소스의 가장 위에 있는 글자를 팝한다

e r i c (top)
e r i c - > r i c e [ i i o i o i o o ]
i i from `e r i c` : `e r i c c i `
o from `e r i c c i ` = `e r i c c`
i from `e r i c` to `e r i c c` : `e r i c c c`
o from `e r i c c c` = `e r i c c` 
i from `e r i c` to `e r i c c` = `e r i c c c`
o o from `e r i c c c` =   `e r i c`

(top)eric
e r i c - > r i c e [ i i o i o i o o ]
i i from `e r i c` to `e r i c` : `e r e r i c`
o from ` e r i c` : `r i c`
i from `r i c` to `e r e r i c`: `r e r e r i c`
..
이것도 틀렸습니다. 

도대체 도대체 도대체 어떻게 하는것인지 이틀째 보고 있는데 모르겠습니다 ㅠㅠ

**Comment by kukukeke** [comment]
다른 예시들을 들어보면 스택이 있고 이걸 stack1이라 할게요.
ERIC - > RICE 로 가는 경우 => 답: i i o i o i o o
순서대로 해볼게요.

i : stack1에 E를 넣는다.                            //   stack1 : E
i: stack1에 R를 넣는다.                            //    stack1 : E R
o: stack1의 top을 뺸다. => R                  // stack1 : E
i: stack1에 I를 넣는다.                              //    stack1 : E I
o: stack1의 top을 뺸다. => I                   //stack1 : E
i: stack1에 C를 넣는다.                          //    stack1 : E C
o: stack1의 top을 뺸다. => C                  // stack1 : E
o: stack1의 top을 뺸다. => E                 // stack1 :

**Comment by jeongm-in** [comment]
그럼
i : 원래 단어의 가장 위에 있는 글자를 pop 해서 stack1에 push
o : stack 1의 가장 위에 있는 글자를 pop 해서 타겟 스택에 push 
가 되겠군요 이제 알겠네요!!!! 고맙습니다
